<?php
if (function_exists('acf_add_local_field_group')) :

	acf_add_local_field_group(array(
		'key' => 'group_6196649d60639',
		'title' => 'Information de l\'évènement',
		'fields' => array(
			array(
				'key' => 'field_619664cbba821',
				'label' => 'Date de l\'évènement',
				'name' => 'event_date',
				'type' => 'date_picker',
				'instructions' => 'Définissez la date de l\'évènement',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'd/m/Y',
				'return_format' => 'j F Y',
				'first_day' => 1,
			),
			array(
				'key' => 'field_6196652eba822',
				'label' => 'Heure de l\'évènement',
				'name' => 'event_hour',
				'type' => 'time_picker',
				'instructions' => 'Définissez l\'heure de début de l\'évènement',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'H:i:s',
				'return_format' => 'H:i:s',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'event',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_619f89d1efe3e',
		'title' => 'Évènement à mettre en avant',
		'fields' => array(
			array(
				'key' => 'field_619f89e0f65ba',
				'label' => 'Évènements',
				'name' => 'events',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'event',
				),
				'taxonomy' => '',
				'allow_null' => 0,
				'multiple' => 1,
				'return_format' => 'id',
				'ui' => 1,
			),
			array(
				'key' => 'field_619f960251395',
				'label' => 'Afficher miniature ?',
				'name' => 'show_thumbnail',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_619f9676679aa',
				'label' => 'Ordre d\'affichage des évènements',
				'name' => 'order',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'ASC' => 'Du plus ancien au plus récent',
					'DESC' => 'Du plus récent au plus ancien',
				),
				'default_value' => 'DESC',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/related-event',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));
endif;
